apiVersion: v1
kind: Service
metadata: 
  name: mymongo
  labels:
    app: mymongo
    lab: kuber-lab1
spec: 
  ports:
    # the port that this service should serve on
    - port: 27017
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: mymongo
