kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mymongopvc
  labels: 
    app: mymongo
    lab: kuber-lab1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
